CREATE SEQUENCE SEQ_Asistencia
    START WITH 1  
    INCREMENT BY 1 ;  
CREATE SEQUENCE SEQ_Aviso
    START WITH 1  
    INCREMENT BY 1 ; 
CREATE SEQUENCE seq_foro
    START WITH 1  
    INCREMENT BY 1 ; 
CREATE SEQUENCE SEQ_Material
    START WITH 1  
    INCREMENT BY 1 ; 
CREATE SEQUENCE SEQ_Notas
    START WITH 1  
    INCREMENT BY 1 ; 
CREATE SEQUENCE SEQ_Tareas
    START WITH 1  
    INCREMENT BY 1 ; 